name: Build from Source



on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt install -y gcc-mingw-w64 g++-mingw-w64
    - name: Build
      run: bash mingw/build-win32.sh
    - name: Archive shipedit
      uses: actions/upload-artifact@v4
      with:
        name: archive shipedit
        path: shipedit-*.zip
